

    def retranslateUi(self, bottomCopyrightWidget):
        _translate = QtCore.QCoreApplication.translate
        bottomCopyrightWidget.setWindowTitle(_translate("bottomCopyrightWidget", "Form"))
        self.label_BottomCopyright_Copyright.setText(_translate("bottomCopyrightWidget", "<html><head/><body><p><a href=\"#\"><span style=\" font-size:12px; color:#FFFFFF;text-decoration:none;\">Copyright ©</span></a></p></body></html>"))
        self.label_BottomCopyright_Site.setText(_translate("bottomCopyrightWidget", "<html><head/><body><p><a href=\"https://loachblog.com\"><span style=\" font-size:12px; color:#FFFFFF;text-decoration:none;\">LoachBlog个人笔记</span></a></p></body></html>"))
        self.label_BottomCopyRight_Line.setText(_translate("bottomCopyrightWidget", "<html><head/><body><p><a href=\"#\"><span style=\" font-size:12px; color:#FFFFFF;text-decoration:none;\">|</span></a></p></body></html>"))
        self.label_BottomCopyright_Beian.setText(_translate("bottomCopyrightWidget", "<html><head/><body><p><a href=\"http://beian.miit.gov.cn/\"><span style=\" font-size:12px; color:#FFFFFF;text-decoration:none;\">粤ICP备16026304号-2</span></a></p></body></html>"))
        Ui_BottomTitleWidget.setWindowTitle(_translate("Ui_BottomTitleWidget", "Form"))
        self.label.setText(_translate("Ui_BottomTitleWidget", "New Posts"))
        self.label_3.setText(_translate("Ui_BottomTitleWidget", "New Tags"))
        self.label_5.setText(_translate("Ui_BottomTitleWidget", "Partners"))
        HeaderMenuWidget.setWindowTitle(_translate("HeaderMenuWidget", "Form"))
        self.pb_Index.setText(_translate("HeaderMenuWidget", "Home"))
        self.pb_Category.setText(_translate("HeaderMenuWidget", "Category"))
        self.pb_DateTime.setText(_translate("HeaderMenuWidget", "Timelines"))
        self.pb_Tags.setText(_translate("HeaderMenuWidget", "Tags"))
        self.pb_About.setText(_translate("HeaderMenuWidget", "About"))
        HeaderTextWidget.setWindowTitle(_translate("HeaderTextWidget", "Form"))
        self.lb_HeaderText1.setText(_translate("HeaderTextWidget", "LoachBlog"))
        self.lb_HeaderText2.setText(_translate("HeaderTextWidget", "Personal Notes"))
        FormPreviewWidget.setWindowTitle(_translate("FormPreviewWidget", "Preview"))
        self.buttonPreviewApply.setText(_translate("FormPreviewWidget", "Apply"))
        RightLoginWidget.setWindowTitle(_translate("RightLoginWidget", "Form"))
        self.lb_Login_Title.setText(_translate("RightLoginWidget", "Person Center"))
        self.clb_Login.setText(_translate("RightLoginWidget", "<html><head/><body><p><a href=\"https://loachblog.com/accounts/login/?\"><span style=\" font-size:14pt; color:#0000ff;text-decoration:none;\">Login</span></a></p></body></html>"))
        RightSearchWidget.setWindowTitle(_translate("RightSearchWidget", "Form"))
        self.lb_Search_Text.setText(_translate("RightSearchWidget", "Search"))
        self.pb_Keyword.setText(_translate("RightSearchWidget", "Search"))
        FormSkinDialog.setWindowTitle(_translate("FormSkinDialog", "Skin"))
        self.labelTitle.setText(_translate("FormSkinDialog", "Skin"))
        self.tabWidgetSkinMain.setTabText(self.tabWidgetSkinMain.indexOf(self.tabTheme), _translate("FormSkinDialog", "Theme"))
        self.tabWidgetSkinMain.setTabText(self.tabWidgetSkinMain.indexOf(self.tabColourful), _translate("FormSkinDialog", "Colourful"))
        self.tabWidgetSkinMain.setTabText(self.tabWidgetSkinMain.indexOf(self.tabPicture), _translate("FormSkinDialog", "Picture"))
        self.label.setText(_translate("FormSkinDialog", "Transparency"))
        self.buttonRestore.setText(_translate("FormSkinDialog", "Restore the default theme"))
        self.label.setText(_translate("FormSkinDialog", "LightGray"))
        self.label.setText(_translate("FormSkinDialog", "DarkBlack"))
        self.label.setText(_translate("FormSkinDialog", "BlueGreen"))
        self.label.setText(_translate("FormSkinDialog", "Orange"))
        self.label.setText(_translate("FormSkinDialog", "Brown"))
        self.label.setText(_translate("FormSkinDialog", "Green"))
        self.label.setText(_translate("FormSkinDialog", "Pink"))
        self.label.setText(_translate("FormSkinDialog", "Purple"))
        self.label.setText(_translate("FormSkinDialog", "Blue"))
        self.label.setText(_translate("FormSkinDialog", "GreyBlue"))
        self.label.setText(_translate("FormSkinDialog", "Blue"))
        self.label.setText(_translate("FormSkinDialog", "Red"))
